#############################################################################
# Makefile for building: Client.app/Contents/MacOS/Client
# Generated by qmake (3.1) (Qt 6.1.3)
# Project:  ../Client/Client.pro
# Template: app
# Command: /Users/y.dyba/Qt/6.1.3/macos/bin/qmake -o Makefile ../Client/Client.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I../Client -I. -I../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers -I../../../Qt/6.1.3/macos/lib/QtGui.framework/Headers -I../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers -I../../../Qt/6.1.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/6.1.3/macos/mkspecs/macx-clang -F/Users/y.dyba/Qt/6.1.3/macos/lib
QMAKE         = /Users/y.dyba/Qt/6.1.3/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/y.dyba/Qt/6.1.3/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/y.dyba/Qt/6.1.3/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Client1.0.0
DISTDIR = /Users/y.dyba/Desktop/Yara_Laba_Server2/build-Client-Qt_6_1_3_for_macOS-Debug/.tmp/Client1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/y.dyba/Qt/6.1.3/macos/lib
LIBS          = $(SUBLIBS) -F/Users/y.dyba/Qt/6.1.3/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Client/main.cpp \
		../Client/mainwindow.cpp \
		../Client/auth.cpp \
		../Client/registration.cpp \
		../Client/tasks.cpp moc_mainwindow.cpp \
		moc_auth.cpp \
		moc_registration.cpp \
		moc_tasks.cpp
OBJECTS       = main.o \
		mainwindow.o \
		auth.o \
		registration.o \
		tasks.o \
		moc_mainwindow.o \
		moc_auth.o \
		moc_registration.o \
		moc_tasks.o
DIST          = ../../../Qt/6.1.3/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.1.3/macos/mkspecs/common/unix.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/mac.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/macx.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/clang.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.1.3/macos/mkspecs/qconfig.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.1.3/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.1.3/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qml_debug.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qt.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/resources.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/moc.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/uic.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/lex.prf \
		../Client/Client.pro ../Client/mainwindow.h \
		../Client/auth.h \
		../Client/registration.h \
		../Client/tasks.h ../Client/main.cpp \
		../Client/mainwindow.cpp \
		../Client/auth.cpp \
		../Client/registration.cpp \
		../Client/tasks.cpp
QMAKE_TARGET  = Client
DESTDIR       = 
TARGET        = Client.app/Contents/MacOS/Client

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/y.dyba/Desktop/Yara_Laba_Server2/Client/Client.pro


include /Users/y.dyba/Qt/6.1.3/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Client.app/Contents/MacOS/Client: ui_mainwindow.h ui_auth.h ui_registration.h ui_tasks.h $(OBJECTS)  
	@test -d Client.app/Contents/MacOS/ || mkdir -p Client.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Client/Client.pro ../../../Qt/6.1.3/macos/mkspecs/macx-clang/qmake.conf ../../../Qt/6.1.3/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.1.3/macos/mkspecs/common/unix.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/mac.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/macx.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/clang.conf \
		../../../Qt/6.1.3/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.1.3/macos/mkspecs/qconfig.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.1.3/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.1.3/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.1.3/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qml_debug.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qt.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/resources.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/moc.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/uic.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.1.3/macos/mkspecs/features/lex.prf \
		../Client/Client.pro \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/6.1.3/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../../Qt/6.1.3/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../Client/Client.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../../../Qt/6.1.3/macos/mkspecs/features/spec_pre.prf:
../../../Qt/6.1.3/macos/mkspecs/features/device_config.prf:
../../../Qt/6.1.3/macos/mkspecs/common/unix.conf:
../../../Qt/6.1.3/macos/mkspecs/common/mac.conf:
../../../Qt/6.1.3/macos/mkspecs/common/macx.conf:
../../../Qt/6.1.3/macos/mkspecs/common/sanitize.conf:
../../../Qt/6.1.3/macos/mkspecs/common/gcc-base.conf:
../../../Qt/6.1.3/macos/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.1.3/macos/mkspecs/common/clang.conf:
../../../Qt/6.1.3/macos/mkspecs/common/clang-mac.conf:
../../../Qt/6.1.3/macos/mkspecs/qconfig.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.1.3/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.1.3/macos/mkspecs/features/qt_functions.prf:
../../../Qt/6.1.3/macos/mkspecs/features/qt_config.prf:
../../../Qt/6.1.3/macos/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.1.3/macos/mkspecs/features/spec_post.prf:
../../../Qt/6.1.3/macos/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/sdk.prf:
../../../Qt/6.1.3/macos/mkspecs/features/toolchain.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.1.3/macos/mkspecs/features/default_pre.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/default_pre.prf:
../../../Qt/6.1.3/macos/mkspecs/features/resolve_config.prf:
../../../Qt/6.1.3/macos/mkspecs/features/default_post.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/default_post.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.1.3/macos/mkspecs/features/qml_debug.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/mac.prf:
../../../Qt/6.1.3/macos/mkspecs/features/warn_on.prf:
../../../Qt/6.1.3/macos/mkspecs/features/qt.prf:
../../../Qt/6.1.3/macos/mkspecs/features/resources_functions.prf:
../../../Qt/6.1.3/macos/mkspecs/features/resources.prf:
../../../Qt/6.1.3/macos/mkspecs/features/moc.prf:
../../../Qt/6.1.3/macos/mkspecs/features/unix/opengl.prf:
../../../Qt/6.1.3/macos/mkspecs/features/uic.prf:
../../../Qt/6.1.3/macos/mkspecs/features/unix/thread.prf:
../../../Qt/6.1.3/macos/mkspecs/features/qmake_use.prf:
../../../Qt/6.1.3/macos/mkspecs/features/file_copies.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/rez.prf:
../../../Qt/6.1.3/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.1.3/macos/mkspecs/features/testcase_targets.prf:
../../../Qt/6.1.3/macos/mkspecs/features/exceptions.prf:
../../../Qt/6.1.3/macos/mkspecs/features/yacc.prf:
../../../Qt/6.1.3/macos/mkspecs/features/lex.prf:
../Client/Client.pro:
../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/6.1.3/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../../Qt/6.1.3/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../Client/Client.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

Client.app/Contents/PkgInfo: 
	@test -d Client.app/Contents || mkdir -p Client.app/Contents
	@$(DEL_FILE) Client.app/Contents/PkgInfo
	@echo "APPL????" > Client.app/Contents/PkgInfo
Client.app/Contents/Resources/empty.lproj: 
	@test -d Client.app/Contents/Resources || mkdir -p Client.app/Contents/Resources
	@touch Client.app/Contents/Resources/empty.lproj
	
Client.app/Contents/Info.plist: 
	@test -d Client.app/Contents || mkdir -p Client.app/Contents
	@$(DEL_FILE) Client.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Client,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Client,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Client,g" -e "s,@LIBRARY@,Client,g" -e "s,\$${EXECUTABLE_NAME},Client,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Qt/6.1.3/macos/mkspecs/macx-clang/Info.plist.app >Client.app/Contents/Info.plist

all: Makefile \
		Client.app/Contents/PkgInfo \
		Client.app/Contents/Resources/empty.lproj \
		Client.app/Contents/Info.plist Client.app/Contents/MacOS/Client

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/6.1.3/macos/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Client/mainwindow.h ../Client/auth.h ../Client/registration.h ../Client/tasks.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Client/main.cpp ../Client/mainwindow.cpp ../Client/auth.cpp ../Client/registration.cpp ../Client/tasks.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Client/mainwindow.ui ../Client/auth.ui ../Client/registration.ui ../Client/tasks.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Client.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/6.1.3/macos/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wall -Wextra -dM -E -o moc_predefs.h ../../../Qt/6.1.3/macos/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_auth.cpp moc_registration.cpp moc_tasks.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_auth.cpp moc_registration.cpp moc_tasks.cpp
moc_mainwindow.cpp: ../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		moc_predefs.h \
		../../../Qt/6.1.3/macos/libexec/moc
	/Users/y.dyba/Qt/6.1.3/macos/libexec/moc $(DEFINES) --include /Users/y.dyba/Desktop/Yara_Laba_Server2/build-Client-Qt_6_1_3_for_macOS-Debug/moc_predefs.h -I/Users/y.dyba/Qt/6.1.3/macos/mkspecs/macx-clang -I/Users/y.dyba/Desktop/Yara_Laba_Server2/Client -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtWidgets.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtGui.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtNetwork.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/y.dyba/Qt/6.1.3/macos/lib ../Client/mainwindow.h -o moc_mainwindow.cpp

moc_auth.cpp: ../Client/auth.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		moc_predefs.h \
		../../../Qt/6.1.3/macos/libexec/moc
	/Users/y.dyba/Qt/6.1.3/macos/libexec/moc $(DEFINES) --include /Users/y.dyba/Desktop/Yara_Laba_Server2/build-Client-Qt_6_1_3_for_macOS-Debug/moc_predefs.h -I/Users/y.dyba/Qt/6.1.3/macos/mkspecs/macx-clang -I/Users/y.dyba/Desktop/Yara_Laba_Server2/Client -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtWidgets.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtGui.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtNetwork.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/y.dyba/Qt/6.1.3/macos/lib ../Client/auth.h -o moc_auth.cpp

moc_registration.cpp: ../Client/registration.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		moc_predefs.h \
		../../../Qt/6.1.3/macos/libexec/moc
	/Users/y.dyba/Qt/6.1.3/macos/libexec/moc $(DEFINES) --include /Users/y.dyba/Desktop/Yara_Laba_Server2/build-Client-Qt_6_1_3_for_macOS-Debug/moc_predefs.h -I/Users/y.dyba/Qt/6.1.3/macos/mkspecs/macx-clang -I/Users/y.dyba/Desktop/Yara_Laba_Server2/Client -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtWidgets.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtGui.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtNetwork.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/y.dyba/Qt/6.1.3/macos/lib ../Client/registration.h -o moc_registration.cpp

moc_tasks.cpp: ../Client/tasks.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		moc_predefs.h \
		../../../Qt/6.1.3/macos/libexec/moc
	/Users/y.dyba/Qt/6.1.3/macos/libexec/moc $(DEFINES) --include /Users/y.dyba/Desktop/Yara_Laba_Server2/build-Client-Qt_6_1_3_for_macOS-Debug/moc_predefs.h -I/Users/y.dyba/Qt/6.1.3/macos/mkspecs/macx-clang -I/Users/y.dyba/Desktop/Yara_Laba_Server2/Client -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtWidgets.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtGui.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtNetwork.framework/Headers -I/Users/y.dyba/Qt/6.1.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/y.dyba/Qt/6.1.3/macos/lib ../Client/tasks.h -o moc_tasks.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_auth.h ui_registration.h ui_tasks.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_auth.h ui_registration.h ui_tasks.h
ui_mainwindow.h: ../Client/mainwindow.ui \
		../../../Qt/6.1.3/macos/libexec/uic
	/Users/y.dyba/Qt/6.1.3/macos/libexec/uic ../Client/mainwindow.ui -o ui_mainwindow.h

ui_auth.h: ../Client/auth.ui \
		../../../Qt/6.1.3/macos/libexec/uic
	/Users/y.dyba/Qt/6.1.3/macos/libexec/uic ../Client/auth.ui -o ui_auth.h

ui_registration.h: ../Client/registration.ui \
		../../../Qt/6.1.3/macos/libexec/uic
	/Users/y.dyba/Qt/6.1.3/macos/libexec/uic ../Client/registration.ui -o ui_registration.h

ui_tasks.h: ../Client/tasks.ui \
		../../../Qt/6.1.3/macos/libexec/uic
	/Users/y.dyba/Qt/6.1.3/macos/libexec/uic ../Client/tasks.ui -o ui_tasks.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../Client/main.cpp ../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		../Client/auth.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Client/main.cpp

mainwindow.o: ../Client/mainwindow.cpp ../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		ui_mainwindow.h \
		../Client/auth.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Client/registration.h \
		../Client/tasks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Client/mainwindow.cpp

auth.o: ../Client/auth.cpp ../Client/auth.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		ui_auth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o auth.o ../Client/auth.cpp

registration.o: ../Client/registration.cpp ../Client/registration.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		ui_registration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registration.o ../Client/registration.cpp

tasks.o: ../Client/tasks.cpp ../Client/tasks.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Client/mainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.1.3/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/QTcpSocket \
		../../../Qt/6.1.3/macos/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		ui_tasks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tasks.o ../Client/tasks.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_auth.o: moc_auth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_auth.o moc_auth.cpp

moc_registration.o: moc_registration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registration.o moc_registration.cpp

moc_tasks.o: moc_tasks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tasks.o moc_tasks.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Client/bin || mkdir -p $(INSTALL_ROOT)/opt/Client/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Client/bin/Client.app
	
	$(QINSTALL) Client.app $(INSTALL_ROOT)/opt/Client/bin/Client.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Client/bin/Client.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Client/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

