#############################################################################
# Makefile for building: echoServer
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  echoServer.pro
# Template: app
# Command: /usr/lib/aarch64-linux-gnu/qt5/bin/qmake -o Makefile echoServer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../include/aarch64-linux-gnu/qt5 -I../../include/aarch64-linux-gnu/qt5/QtNetwork -I../../include/aarch64-linux-gnu/qt5/QtCore -I. -I../../lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/aarch64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = echoServer1.0.0
DISTDIR = /usr/src/myapp/.tmp/echoServer1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Network -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mytcpserver.cpp moc_mytcpserver.cpp
OBJECTS       = main.o \
		mytcpserver.o \
		moc_mytcpserver.o
DIST          = ../../lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		echoServer.pro mytcpserver.h main.cpp \
		mytcpserver.cpp
QMAKE_TARGET  = echoServer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = echoServer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: echoServer.pro ../../lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf ../../lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		../../lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		echoServer.pro \
		/usr/lib/aarch64-linux-gnu/libQt5Network.prl \
		/usr/lib/aarch64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile echoServer.pro
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/c++11.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf:
../../lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf:
echoServer.pro:
/usr/lib/aarch64-linux-gnu/libQt5Network.prl:
/usr/lib/aarch64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile echoServer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mytcpserver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mytcpserver.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mytcpserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mytcpserver.cpp
moc_mytcpserver.cpp: ../../include/aarch64-linux-gnu/qt5/QtCore/QObject \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qnamespace.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qglobal.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qconfig.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfeatures.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtypetraits.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsysinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlogging.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qflags.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_gcc.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv7.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv6.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv5.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_ia64.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_x86.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_unix.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmutex.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qnumeric.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstring.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qchar.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrefcount.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qalgorithms.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qiterator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qregexp.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcoreevent.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qisenum.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobject_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QTcpServer \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtcpserver.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qabstractsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qiodevice.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdebug.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qhash.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpair.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmap.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextstream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlocale.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvariant.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qshareddata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvector.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpoint.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qset.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhostaddress.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QTcpSocket \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtcpsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QtNetwork \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QtNetworkDepends \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtCore \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtCoreDepends \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qparallelanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpauseanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpropertyanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvariantanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeasingcurve.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsequentialanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextcodec.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qendian.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlibraryinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdatetime.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbuffer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdatastream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdir.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfileinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfiledevice.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdiriterator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfileselector.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QStringList \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfilesystemwatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlockfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qloggingcategory.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qprocess.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qresource.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsavefile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsettings.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstandardpaths.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstorageinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtemporarydir.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QScopedPointer \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtemporaryfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qurl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qurlquery.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qidentityproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsortfilterproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringlistmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonarray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonvalue.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsondocument.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstracteventdispatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeventloop.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractnativeeventfilter.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbasictimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmath.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmetaobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimedata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectcleanuphandler.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedmemory.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsignalmapper.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsocketnotifier.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsystemsemaphore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtranslator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qwineventnotifier.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimedatabase.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimetype.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfactoryinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlibrary.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qplugin.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpluginloader.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/quuid.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstracttransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeventtransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfinalstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qhistorystate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsignaltransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstatemachine.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qexception.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuture.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfutureinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrunnable.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qresultstore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuturesynchronizer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuturewatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qreadwritelock.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsemaphore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthread.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthreadpool.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthreadstorage.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qwaitcondition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydataops.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydatapointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbitarray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearraymatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcache.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcollator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcommandlineoption.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcommandlineparser.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcryptographichash.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qelapsedtimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qline.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlinkedlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmargins.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmessageauthenticationcode.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qqueue.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrect.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsize.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qregularexpression.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qscopedvaluerollback.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstack.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextboundaryfinder.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimeline.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimezone.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qxmlstream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtcoreversion.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qabstractnetworkcache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkrequest.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QSharedDataPointer \
		../../include/aarch64-linux-gnu/qt5/QtCore/QString \
		../../include/aarch64-linux-gnu/qt5/QtCore/QUrl \
		../../include/aarch64-linux-gnu/qt5/QtCore/QVariant \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhttpmultipart.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QByteArray \
		../../include/aarch64-linux-gnu/qt5/QtCore/QIODevice \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QNetworkRequest \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkaccessmanager.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QSslConfiguration \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslconfiguration.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslerror.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcertificate.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qssl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QFlags \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtGlobal \
		../../include/aarch64-linux-gnu/qt5/QtCore/QMetaType \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkcookie.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QList \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkcookiejar.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkdiskcache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkreply.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QNetworkAccessManager \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkconfigmanager.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkconfiguration.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworksession.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qauthenticator.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qdnslookup.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhostinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkproxy.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qlocalserver.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qlocalsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qudpsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcertificateextension.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcipher.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslellipticcurve.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QHash \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslkey.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtnetworkversion.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QDebug \
		mytcpserver.h
	/usr/lib/aarch64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/src/myapp -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/aarch64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/aarch64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/aarch64-linux-gnu/5/include-fixed -I/usr/include/aarch64-linux-gnu -I/usr/include mytcpserver.h -o moc_mytcpserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../include/aarch64-linux-gnu/qt5/QtCore/QCoreApplication \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qglobal.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qconfig.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfeatures.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtypetraits.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsysinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlogging.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qflags.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_gcc.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv7.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv6.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv5.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_ia64.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_x86.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_unix.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmutex.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qnumeric.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstring.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qchar.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrefcount.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qnamespace.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qalgorithms.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qiterator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qregexp.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcoreevent.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qisenum.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobject_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeventloop.h \
		mytcpserver.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QObject \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QTcpServer \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtcpserver.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qabstractsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qiodevice.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdebug.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qhash.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpair.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmap.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextstream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlocale.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvariant.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qshareddata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvector.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpoint.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qset.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhostaddress.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QTcpSocket \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtcpsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QtNetwork \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QtNetworkDepends \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtCore \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtCoreDepends \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qparallelanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpauseanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpropertyanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvariantanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeasingcurve.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsequentialanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextcodec.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qendian.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlibraryinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdatetime.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbuffer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdatastream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdir.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfileinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfiledevice.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdiriterator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfileselector.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QStringList \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfilesystemwatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlockfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qloggingcategory.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qprocess.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qresource.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsavefile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsettings.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstandardpaths.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstorageinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtemporarydir.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QScopedPointer \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtemporaryfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qurl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qurlquery.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qidentityproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsortfilterproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringlistmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonarray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonvalue.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsondocument.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstracteventdispatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractnativeeventfilter.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbasictimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmath.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmetaobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimedata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectcleanuphandler.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedmemory.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsignalmapper.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsocketnotifier.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsystemsemaphore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtranslator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qwineventnotifier.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimedatabase.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimetype.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfactoryinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlibrary.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qplugin.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpluginloader.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/quuid.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstracttransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeventtransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfinalstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qhistorystate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsignaltransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstatemachine.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qexception.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuture.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfutureinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrunnable.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qresultstore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuturesynchronizer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuturewatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qreadwritelock.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsemaphore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthread.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthreadpool.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthreadstorage.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qwaitcondition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydataops.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydatapointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbitarray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearraymatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcache.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcollator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcommandlineoption.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcommandlineparser.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcryptographichash.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qelapsedtimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qline.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlinkedlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmargins.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmessageauthenticationcode.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qqueue.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrect.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsize.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qregularexpression.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qscopedvaluerollback.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstack.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextboundaryfinder.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimeline.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimezone.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qxmlstream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtcoreversion.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qabstractnetworkcache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkrequest.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QSharedDataPointer \
		../../include/aarch64-linux-gnu/qt5/QtCore/QString \
		../../include/aarch64-linux-gnu/qt5/QtCore/QUrl \
		../../include/aarch64-linux-gnu/qt5/QtCore/QVariant \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhttpmultipart.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QByteArray \
		../../include/aarch64-linux-gnu/qt5/QtCore/QIODevice \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QNetworkRequest \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkaccessmanager.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QSslConfiguration \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslconfiguration.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslerror.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcertificate.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qssl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QFlags \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtGlobal \
		../../include/aarch64-linux-gnu/qt5/QtCore/QMetaType \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkcookie.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QList \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkcookiejar.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkdiskcache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkreply.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QNetworkAccessManager \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkconfigmanager.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkconfiguration.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworksession.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qauthenticator.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qdnslookup.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhostinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkproxy.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qlocalserver.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qlocalsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qudpsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcertificateextension.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcipher.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslellipticcurve.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QHash \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslkey.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtnetworkversion.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mytcpserver.o: mytcpserver.cpp mytcpserver.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QObject \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qnamespace.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qglobal.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qconfig.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfeatures.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtypetraits.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsysinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlogging.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qflags.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_gcc.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv7.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv6.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_armv5.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_ia64.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_x86.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qatomic_unix.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmutex.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qnumeric.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstring.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qchar.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrefcount.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qalgorithms.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qiterator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qregexp.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcoreevent.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qisenum.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobject_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QTcpServer \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtcpserver.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qabstractsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qiodevice.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdebug.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qhash.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpair.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmap.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextstream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlocale.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvariant.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qshareddata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvector.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpoint.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qset.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhostaddress.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QTcpSocket \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtcpsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QtNetwork \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QtNetworkDepends \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtCore \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtCoreDepends \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qparallelanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpauseanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpropertyanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qvariantanimation.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeasingcurve.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsequentialanimationgroup.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextcodec.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qendian.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlibraryinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdatetime.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbuffer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdatastream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdir.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfileinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfiledevice.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qdiriterator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfileselector.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QStringList \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfilesystemwatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlockfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qloggingcategory.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qprocess.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qresource.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsavefile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsettings.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstandardpaths.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstorageinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtemporarydir.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QScopedPointer \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtemporaryfile.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qurl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qurlquery.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractitemmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qidentityproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qitemselectionmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsortfilterproxymodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstringlistmodel.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonarray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonvalue.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsondocument.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qjsonobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstracteventdispatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeventloop.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractnativeeventfilter.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbasictimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmath.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmetaobject.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimedata.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qobjectcleanuphandler.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsharedmemory.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsignalmapper.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsocketnotifier.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsystemsemaphore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtranslator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qwineventnotifier.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimedatabase.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmimetype.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfactoryinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlibrary.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qplugin.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qpluginloader.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/quuid.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstractstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qabstracttransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qeventtransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfinalstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qhistorystate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsignaltransition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstate.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstatemachine.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qexception.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuture.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfutureinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrunnable.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qresultstore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuturesynchronizer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qfuturewatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qreadwritelock.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsemaphore.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthread.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthreadpool.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qthreadstorage.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qwaitcondition.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydataops.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qarraydatapointer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbitarray.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qbytearraymatcher.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcache.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcollator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcommandlineoption.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcommandlineparser.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qcryptographichash.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qelapsedtimer.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qline.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qlinkedlist.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmargins.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qmessageauthenticationcode.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qqueue.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qrect.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qsize.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qregularexpression.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qscopedvaluerollback.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qstack.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtextboundaryfinder.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimeline.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtimezone.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qxmlstream.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/qtcoreversion.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qabstractnetworkcache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkrequest.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QSharedDataPointer \
		../../include/aarch64-linux-gnu/qt5/QtCore/QString \
		../../include/aarch64-linux-gnu/qt5/QtCore/QUrl \
		../../include/aarch64-linux-gnu/qt5/QtCore/QVariant \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhttpmultipart.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QByteArray \
		../../include/aarch64-linux-gnu/qt5/QtCore/QIODevice \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QNetworkRequest \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkaccessmanager.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QSslConfiguration \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslconfiguration.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslerror.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcertificate.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qssl.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QFlags \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QtGlobal \
		../../include/aarch64-linux-gnu/qt5/QtCore/QMetaType \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkcookie.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QList \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkcookiejar.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkdiskcache.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkreply.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/QNetworkAccessManager \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkconfigmanager.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkconfiguration.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworksession.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkinterface.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qauthenticator.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qdnslookup.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qhostinfo.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qnetworkproxy.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qlocalserver.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qlocalsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qudpsocket.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcertificateextension.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslcipher.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslellipticcurve.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QHash \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qsslkey.h \
		../../include/aarch64-linux-gnu/qt5/QtNetwork/qtnetworkversion.h \
		../../include/aarch64-linux-gnu/qt5/QtCore/QDebug \
		../../include/aarch64-linux-gnu/qt5/QtCore/QCoreApplication
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytcpserver.o mytcpserver.cpp

moc_mytcpserver.o: moc_mytcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mytcpserver.o moc_mytcpserver.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/echoServer/bin || mkdir -p $(INSTALL_ROOT)/opt/echoServer/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/echoServer/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/echoServer/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/echoServer/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/echoServer/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

